version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - app/.env
  web:
    image: mvrogozov/museum_news_fastapi:v0.0.2
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - app/.env